version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:16

jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run: npm install
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Build package
          command: npm run build

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - store_test_results:
          path: coverage

      - persist_to_workspace:
          root: ~/repo
          paths: .
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: |
            if [[ "${CIRCLE_TAG}" == *"beta"* ]]; then
              npm publish --tag beta
            else
              npm publish
            fi

workflows:
  version: 2
  test-publish:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
      - publish:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
